import { AlertTriangle, Shield, FileText, Scale } from "lucide-react";

export default function Disclaimer() {
  return (
    <div className="min-h-screen bg-gradient-to-br from-[#0f172a] via-[#1e293b] to-[#0f172a] py-40">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <div className="bg-white/5 backdrop-blur-xl border border-white/10 rounded-2xl shadow-xl shadow-[#00C2FF]/20 p-8 md:p-12">
          {/* Header */}
          <div className="text-center mb-12">
            <AlertTriangle className="h-16 w-16 text-yellow-400 mx-auto mb-4" />
            <h1 className="text-4xl font-bold text-white mb-4 bg-gradient-to-r from-white via-gray-200 to-white bg-clip-text text-transparent">
              Legal Disclaimer
            </h1>
            <p className="text-gray-300 text-xl">
              Important information about using JurisAssist
            </p>
          </div>

          {/* Key Disclaimer Points */}
          <div className="space-y-6">
            <div className="bg-white/5 border-l-4 border-yellow-400 p-6 mb-6 rounded-r-xl">
              <div className="flex items-start">
                <AlertTriangle className="h-6 w-6 text-yellow-400 mr-3 flex-shrink-0 mt-1" />
                <div>
                  <h3 className="text-lg font-bold text-white mb-2">
                    Not a Substitute for Legal Advice
                  </h3>
                  <p className="text-gray-300">
                    JurisAssist is an educational tool and does NOT provide legal advice.
                    The information provided by our AI is for general informational purposes
                    only and should not be relied upon as legal counsel.
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-white/5 rounded-xl p-6">
              <div className="flex items-start">
                <Scale className="h-8 w-8 text-blue-400 mr-4 flex-shrink-0" />
                <div>
                  <h2 className="text-xl font-bold text-white mb-3">
                    No Attorney-Client Relationship
                  </h2>
                  <p className="text-gray-300 leading-relaxed">
                    Using JurisAssist does not create an attorney-client relationship between
                    you and JurisAssist, its operators, or any affiliated attorneys. Any
                    information you provide is not protected by attorney-client privilege.
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-white/5 rounded-xl p-6">
              <div className="flex items-start">
                <FileText className="h-8 w-8 text-green-400 mr-4 flex-shrink-0" />
                <div>
                  <h2 className="text-xl font-bold text-white mb-3">AI-Generated Content</h2>
                  <p className="text-gray-300 leading-relaxed">
                    Our analysis is generated by AI and may contain errors, omissions, or
                    inaccuracies. AI technology, while advanced, is not perfect and should not
                    be solely relied upon for important legal decisions.
                  </p>
                </div>
              </div>
            </div>

            <div className="bg-white/5 rounded-xl p-6">
              <div className="flex items-start">
                <Shield className="h-8 w-8 text-red-400 mr-4 flex-shrink-0" />
                <div>
                  <h2 className="text-xl font-bold text-white mb-3">
                    Accuracy and Reliability
                  </h2>
                  <p className="text-gray-300 leading-relaxed">
                    While we strive for accuracy, we make no warranties or guarantees about the
                    completeness, reliability, or accuracy of the information provided. Laws
                    vary by jurisdiction and change frequently.
                  </p>
                </div>
              </div>
            </div>
          </div>

          {/* Additional Sections */}
          <div className="mt-8 space-y-6">
            <h2 className="text-2xl font-bold text-white mb-4">
              When You Should Consult an Attorney
            </h2>
            <ul className="space-y-2 text-gray-300 list-inside">
              <li>• You are involved in litigation or legal proceedings</li>
              <li>• You need to sign important contracts or agreements</li>
              <li>• Significant money or property rights are at stake</li>
              <li>• You are facing criminal charges</li>
              <li>• You are dealing with estate planning or complex tax issues</li>
              <li>• Your situation involves multiple parties or jurisdictions</li>
              <li>• You are unsure about your legal rights or obligations</li>
            </ul>

            <h2 className="text-2xl font-bold text-white mb-4 mt-6">Limitation of Liability</h2>
            <p className="text-gray-300 leading-relaxed">
              JurisAssist, its operators, and affiliates shall not be liable for any damages,
              losses, or legal consequences resulting from the use or reliance on information
              provided through this service. You use JurisAssist at your own risk.
            </p>

            <h2 className="text-2xl font-bold text-white mb-4 mt-6">Privacy and Security</h2>
            <p className="text-gray-300 leading-relaxed">
              While we take reasonable measures to protect your information, any data you upload
              or submit is processed by our AI system. Do not submit highly sensitive or
              confidential information without understanding the privacy implications.
            </p>

            <h2 className="text-2xl font-bold text-white mb-4 mt-6">Jurisdiction-Specific Laws</h2>
            <p className="text-gray-300 leading-relaxed">
              Laws vary significantly by country, state, and locality. Our AI provides general
              information and may not account for the specific laws in your jurisdiction. Always
              verify information with local legal resources or attorneys.
            </p>

            {/* Acknowledgment Box */}
            <div className="bg-gradient-to-r from-[#00C2FF]/30 to-[#00FF88]/30 rounded-2xl p-6 mt-8">
              <h3 className="text-xl font-bold text-white mb-2">By Using JurisAssist, You Acknowledge:</h3>
              <ul className="space-y-2 text-white">
                <li>• You understand this is not legal advice</li>
                <li>• You will not rely solely on AI-generated information for legal decisions</li>
                <li>• You will consult a qualified attorney for serious legal matters</li>
                <li>• You accept full responsibility for how you use the information provided</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}
